[project]
name = "integration-with-sqlalchemy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pymongo>=4.15.4",
    "sqlalchemy>=2.0.44",
]
